services:
  web:
    #build: .
    image: "beggar:t3"
    ports:
      - "3001:3000"
    environment:
      RAILS_ENV: development
    depends_on: 
      - redis
  redis:
    image: "redis:latest"
    ports: 
      - "6379:6379"
